### ISSUE TITLE
Sorting by "Date Received" not functional

### ISSUE THREAD

**Issue by rutkovskii** [Taequn/lightyear#33]

**Comment by rutkovskii** [comment]
Searches for Date Received now.
It was confusing for me for a second why it did not search for 2022-03-20, but then I realised it was the weekend.

**Comment by liam-murphy14** [comment]
this issue is still not resolved. The search works but the SORTING feature does not. I will take a look now

**Comment by liam-murphy14** [comment]
Now I actually fixed it, and cleaned up the db to boot
